// Generated by Makefile - do not edit

import Foundation

struct SampleMIDIFile: Sendable, Equatable {
    let title: String
    let assetName: String
}

enum SampleMIDIFiles {
    static let all: [SampleMIDIFile] = [
        SampleMIDIFile(title: "Chopin - Op. 28 No. 20", assetName: "Chopin - Op. 28 No. 20"),
        SampleMIDIFile(title: "Debussy - Clair de Lune", assetName: "Debussy - Clair de Lune"),
        SampleMIDIFile(title: "Rachmaninoff - Op. 3 No. 2", assetName: "Rachmaninoff - Op. 3 No. 2")
    ]
}
