.PHONY: build build-release-unsigned generate-appicons add-midi-assets \
	add-soundbank-assets test clean generate-build-info lint lint-fix-safe \
	run-sim-ipad-pro run-sim-iphone-pro run-sim-iphone-max sim-run-my-mac

SWIFTLINT ?= $(shell command -v swiftlint 2>/dev/null)

# Must match the Xcode scheme name and the on-disk folder `MIDI Scribe/`.
PROJECT := MIDI Scribe.xcodeproj
XCODE_SCHEME := MIDI Scribe
APP_NAME := MIDI Scribe
APP_DIR := MIDI Scribe
BUNDLE_ID ?= org.centennialoss.midiscribe
DERIVED_DATA := build/DerivedData
DIST_DERIVED_DATA := dist/DerivedData

# App icon pipeline:
#   1. Composite assets/app-icon-large-transparent.png over assets/app-icon-background-large.png → assets/app-icon-large.png
#   2. Resize the composite to 1024x1024 → AppIcon_1024.png
#   3. Generate smaller icons directly from the original composite to avoid cascading resizes.
APPICON_DIR := $(APP_DIR)/Assets.xcassets/AppIcon.appiconset
APPICON_SRC := $(APPICON_DIR)/AppIcon_1024.png
APPICON_SIZES := 16 32 64 128 256 512
APPICON_BG := assets/app-icon-background-large.png
APPICON_LARGE := assets/app-icon-large.png
APPICON_PREVIEW := assets/app-icon.png
MIDI_ASSET_SCRIPT := scripts/add-midi-assets.swift
MIDI_TESTDATA_DIR := testdata
MIDI_SAMPLE_ASSET_DIR := $(APP_DIR)/Assets.xcassets/SampleTakes
MIDI_SAMPLE_MANIFEST := $(APP_DIR)/Data/SampleMIDIFiles.generated.swift
SOUNDBANK_ASSET_SCRIPT := scripts/add-soundbank-assets.swift
SOUNDBANK_SOURCE := soundbanks/GeneralUser-GS/GeneralUser-GS.sf2
SOUNDBANK_ASSET_DIR := $(APP_DIR)/Assets.xcassets/SoundBanks
SOUNDBANK_MANIFEST := $(APP_DIR)/Data/SoundBankAssets.generated.swift

# Transparent icon: source of truth is assets/app-icon-large-transparent.png → 128x128 to both:
APPICON_TRANSPARENT_SRC := assets/app-icon-large-transparent.png
APPICON_TRANSPARENT_128 := assets/app-icon-transparent.png
APPICON_TRANSPARENT_IMAGESET := $(APP_DIR)/Assets.xcassets/AppIconTransparent.imageset/app-icon-transparent.png

# Build info generation: BuildInfo.generated.swift used by BuildInfo.swift.
# These defaults can be overridden by environment variables, e.g.:
#   COMMIT=... DATE=... CONFIG=Release ARCH=arm64 make generate-build-info
COMMIT ?= $(shell git rev-parse HEAD 2>/dev/null || echo local)
DATE ?= $(shell date -u +"%Y-%m-%dT%H:%M:%S.000Z")
CONFIG ?= Debug
ARCH ?= arm64

# Override version at build time (e.g. TAGVER=1.0.0-demo make build-release-unsigned).
# Writes $(APP_DIR)/Version.xcconfig so the app shows this version in About and Info.plist.
TAGVER ?=

lint:
	@if [ -z "$(SWIFTLINT)" ]; then \
		echo "SwiftLint not found. Install with: brew install swiftlint" >&2; \
		exit 1; \
	fi
	@"$(SWIFTLINT)" lint --strict $(FIX_PATHS)

# Autocorrect only low-risk rules (whitespace / file hygiene). Still review `git diff` and run tests.
# Optional: pass paths (quote if they contain spaces), e.g. `make lint-fix-safe FIX_PATHS='"MIDI Scribe/ContentView.swift"'`
FIX_PATHS ?= "MIDI Scribe" "MIDI ScribeTests" "MIDI ScribeUITests"
lint-fix-safe:
	@if [ -z "$(SWIFTLINT)" ]; then \
		echo "SwiftLint not found. Install with: brew install swiftlint" >&2; \
		exit 1; \
	fi
	@"$(SWIFTLINT)" lint --fix \
		--only-rule trailing_whitespace \
		--only-rule trailing_newline \
		--only-rule leading_whitespace \
		--only-rule trailing_semicolon \
		$(FIX_PATHS)

clean:
	@rm -rf build dist ; rm -rf ~/Library/Developer/Xcode/DerivedData/MIDI_Scribe-*

generate-build-info:
	@printf '// Generated by Makefile - do not edit\nenum BuildInfoGenerated {\n    static let buildCommit = "%s"\n    static let buildDate = "%s"\n    static let buildConfiguration = "%s"\n    static let buildArch = "%s"\n}\n' "$(COMMIT)" "$(DATE)" "$(CONFIG)" "$(ARCH)" > "$(APP_DIR)/Data/BuildInfo.generated.swift"

add-midi-assets:
	@swift "$(MIDI_ASSET_SCRIPT)" "$(MIDI_TESTDATA_DIR)" "$(MIDI_SAMPLE_ASSET_DIR)" "$(MIDI_SAMPLE_MANIFEST)"

add-soundbank-assets:
	@swift "$(SOUNDBANK_ASSET_SCRIPT)" "$(SOUNDBANK_SOURCE)" "$(SOUNDBANK_ASSET_DIR)" "$(SOUNDBANK_MANIFEST)"

build: test build-macos build-ios

build-macos: 
	mkdir -p build
	xcodebuild -project "$(PROJECT)" -scheme "$(XCODE_SCHEME)" -configuration Debug -derivedDataPath $(DERIVED_DATA) -destination 'platform=macOS' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
	cp -R "$(DERIVED_DATA)/Build/Products/Debug/$(APP_NAME).app" build/

build-ios: 
	mkdir -p build
	xcodebuild -project "$(PROJECT)" -scheme "$(XCODE_SCHEME)" -configuration Debug -derivedDataPath $(DERIVED_DATA) -destination 'generic/platform=iOS Simulator' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
	cp -R "$(DERIVED_DATA)/Build/Products/Debug-iphonesimulator/$(APP_NAME).app" "build/$(APP_NAME)-iPad.app"

build-release-unsigned:
	mkdir -p dist
	@if [ -n "$(TAGVER)" ]; then \
		printf 'MARKETING_VERSION = %s\nINFOPLIST_KEY_NSHumanReadableCopyright = Copyright © 2026 Centennial OSS\n' "$(TAGVER)" > "$(APP_DIR)/Version.xcconfig"; \
	fi
	xcodebuild -scheme "$(XCODE_SCHEME)" -configuration Release -derivedDataPath dist/DerivedData build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
	cp -R "dist/DerivedData/Build/Products/Release/MIDI Scribe.app" dist/

# Run Swift tests.
test: lint
	mkdir -p build
	xcodebuild test -scheme "$(XCODE_SCHEME)" -configuration Debug -derivedDataPath build/DerivedData -destination 'platform=macOS' -skip-testing:"MIDI ScribeUITests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

# Generate app icon: composite transparent onto background → app-icon-large.png, then render AppIcon_1024 and smaller sizes.
# Composite uses Swift script (no extra deps on macOS). 16 and 32: center-crop then resize; 64,128,256,512: resize only.
generate-appicons:
	@test -f "$(APPICON_BG)" || (echo "Missing: $(APPICON_BG)" && exit 1)
	@test -f "$(APPICON_TRANSPARENT_SRC)" || (echo "Missing: $(APPICON_TRANSPARENT_SRC)" && exit 1)
	@echo "Compositing app-icon-large-transparent.png onto app-icon-background-large.png -> app-icon-large.png"
	@swift scripts/composite-app-icon.swift "$(APPICON_BG)" "$(APPICON_TRANSPARENT_SRC)" "$(APPICON_LARGE)"
	@echo "Creating AppIcon_1024.png from original composite"
	@sips -z 1024 1024 "$(APPICON_LARGE)" --out "$(APPICON_SRC)"
	@for size in $(APPICON_SIZES); do \
		echo "Creating AppIcon_$$size.png from original composite"; \
		if [ "$$size" = "16" ]; then \
			sips --cropToHeightWidth 780 780 "$(APPICON_LARGE)" --out /tmp/AppIcon_crop.png && \
			sips -z 16 16 /tmp/AppIcon_crop.png --out "$(APPICON_DIR)/AppIcon_16.png"; \
		elif [ "$$size" = "32" ]; then \
			sips --cropToHeightWidth 880 880 "$(APPICON_LARGE)" --out /tmp/AppIcon_crop.png && \
			sips -z 32 32 /tmp/AppIcon_crop.png --out "$(APPICON_DIR)/AppIcon_32.png"; \
		else \
			sips -z $$size $$size --out "$(APPICON_DIR)/AppIcon_$$size.png" "$(APPICON_LARGE)"; \
		fi; \
	done
	@cp "$(APPICON_DIR)/AppIcon_128.png" "$(APPICON_PREVIEW)"
	@rm -f /tmp/AppIcon_crop.png
	@echo "Done writing AppIcons and $(APPICON_PREVIEW)"

# Simulator / run helpers (placeholders — wire up xcodebuild/xcrun simctl as needed).
run-sim-ipad-pro:
	@echo "TODO: run-sim-ipad-pro (iPad Pro simulator)"

run-sim-iphone-pro:
	@echo "TODO: run-sim-iphone-pro (iPhone Pro simulator)"

run-sim-iphone-max:
	@echo "TODO: run-sim-iphone-max (iPhone Pro Max simulator)"

sim-run-my-mac:
	@echo "TODO: sim-run-my-mac (run on My Mac / designed for iPad on Mac)"

reset-defaults:
	@defaults delete $(BUNDLE_ID) 2>/dev/null || true
	@rm -f "$(HOME)/Library/Preferences/$(BUNDLE_ID).plist"
	@rm -f "$(HOME)/Library/Containers/$(BUNDLE_ID)/Data/Library/Preferences/$(BUNDLE_ID).plist"
	@echo "Reset UserDefaults for $(BUNDLE_ID) (including sandbox container prefs)"
