// Generated by Makefile - do not edit

import Foundation

struct SampleMIDIFile: Sendable, Equatable {
    let title: String
    let assetName: String
}

enum SampleMIDIFiles {
    static let all: [SampleMIDIFile] = [
        SampleMIDIFile(title: "Chopin - Prelude O28 N20", assetName: "Chopin - Prelude O28 N20"),
        SampleMIDIFile(title: "Debussy - Clair de Lune", assetName: "Debussy - Clair de Lune"),
        SampleMIDIFile(title: "Rachmaninov - Prelude O3 N2", assetName: "Rachmaninov - Prelude O3 N2")
    ]
}
