// Generated by Makefile - do not edit

import Foundation
#if os(macOS)
import AppKit
#elseif os(iOS)
import UIKit
#endif

enum SoundBankAssets {
    static let assetName = "GeneralUser-GS"
    static let assetPath = "SoundBanks/\(assetName)"
    static let fileName = "GeneralUser-GS.sf2"

    static func soundBankURL() throws -> URL {
        if let url = Bundle.main.url(forResource: assetName, withExtension: "sf2") {
            return url
        }
        guard let asset = NSDataAsset(name: assetPath) ?? NSDataAsset(name: assetName) else {
            throw CocoaError(.fileNoSuchFile)
        }
        let directory = try FileManager.default.url(
            for: .cachesDirectory, in: .userDomainMask, appropriateFor: nil, create: true
        ).appendingPathComponent("SoundBanks", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent(fileName)
        if !FileManager.default.fileExists(atPath: url.path) {
            try asset.data.write(to: url, options: Data.WritingOptions.atomic)
        }
        return url
    }
}
