#!/usr/bin/env swift

import Foundation

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data((message + "\n").utf8))
    exit(1)
}

guard CommandLine.arguments.count == 4 else {
    fail("Usage: add-soundbank-assets.swift <soundbank-path> <asset-output-dir> <manifest-output-path>")
}

let fileManager = FileManager.default
let sourceURL = URL(fileURLWithPath: CommandLine.arguments[1])
let assetRootURL = URL(fileURLWithPath: CommandLine.arguments[2], isDirectory: true)
let manifestURL = URL(fileURLWithPath: CommandLine.arguments[3])

guard fileManager.fileExists(atPath: sourceURL.path) else {
    fail("Missing soundbank: \(sourceURL.path)")
}

let assetName = sourceURL.deletingPathExtension().lastPathComponent
let datasetURL = assetRootURL.appendingPathComponent("\(assetName).dataset", isDirectory: true)
let destinationURL = datasetURL.appendingPathComponent(sourceURL.lastPathComponent)

try fileManager.createDirectory(at: assetRootURL, withIntermediateDirectories: true)
try """
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
""".write(to: assetRootURL.appendingPathComponent("Contents.json"), atomically: true, encoding: .utf8)

let existingChildren = try fileManager.contentsOfDirectory(at: assetRootURL, includingPropertiesForKeys: nil)
for child in existingChildren where child.pathExtension == "dataset" {
    try fileManager.removeItem(at: child)
}

try fileManager.createDirectory(at: datasetURL, withIntermediateDirectories: true)
try fileManager.copyItem(at: sourceURL, to: destinationURL)
try """
{
  "data" : [
    {
      "filename" : "\(sourceURL.lastPathComponent)"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
""".write(to: datasetURL.appendingPathComponent("Contents.json"), atomically: true, encoding: .utf8)

let manifest = """
// Generated by Makefile - do not edit

import Foundation
#if os(macOS)
import AppKit
#elseif os(iOS)
import UIKit
#endif

enum SoundBankAssets {
    static let assetName = "\(assetName)"
    static let assetPath = "SoundBanks/\\(assetName)"
    static let fileName = "\(sourceURL.lastPathComponent)"

    static func soundBankURL() throws -> URL {
        if let url = Bundle.main.url(forResource: assetName, withExtension: "sf2") {
            return url
        }
        guard let asset = NSDataAsset(name: assetPath) ?? NSDataAsset(name: assetName) else {
            throw CocoaError(.fileNoSuchFile)
        }
        let directory = try FileManager.default.url(
            for: .cachesDirectory, in: .userDomainMask, appropriateFor: nil, create: true
        ).appendingPathComponent("SoundBanks", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent(fileName)
        if !FileManager.default.fileExists(atPath: url.path) {
            try asset.data.write(to: url, options: Data.WritingOptions.atomic)
        }
        return url
    }
}

"""

try fileManager.createDirectory(at: manifestURL.deletingLastPathComponent(), withIntermediateDirectories: true)
try manifest.write(to: manifestURL, atomically: true, encoding: .utf8)

print("Wrote soundbank asset \(assetName)")
