#!/usr/bin/env swift

import Foundation

struct SampleFile {
    let sourceURL: URL
    let title: String
    let assetName: String
}

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data((message + "\n").utf8))
    exit(1)
}

guard CommandLine.arguments.count == 4 else {
    fail("Usage: add-midi-assets.swift <testdata-dir> <asset-output-dir> <manifest-output-path>")
}

let fileManager = FileManager.default
let testdataURL = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
let assetRootURL = URL(fileURLWithPath: CommandLine.arguments[2], isDirectory: true)
let manifestURL = URL(fileURLWithPath: CommandLine.arguments[3])

guard let enumerator = fileManager.enumerator(
    at: testdataURL,
    includingPropertiesForKeys: [.isRegularFileKey],
    options: [.skipsHiddenFiles]
) else {
    fail("Unable to scan \(testdataURL.path)")
}

let samples: [SampleFile] = enumerator.compactMap { item in
    guard let url = item as? URL else { return nil }
    guard url.pathExtension.lowercased() == "mid" else { return nil }
    let values = try? url.resourceValues(forKeys: [.isRegularFileKey])
    guard values?.isRegularFile == true else { return nil }
    let title = url.deletingPathExtension().lastPathComponent
    let assetName = title
        .replacingOccurrences(of: "/", with: "-")
        .replacingOccurrences(of: ":", with: "-")
    return SampleFile(sourceURL: url, title: title, assetName: assetName)
}.sorted { $0.title.localizedStandardCompare($1.title) == .orderedAscending }

try fileManager.createDirectory(at: assetRootURL, withIntermediateDirectories: true)

let rootContents = """
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
"""
try rootContents.write(to: assetRootURL.appendingPathComponent("Contents.json"), atomically: true, encoding: .utf8)

let existingChildren = try fileManager.contentsOfDirectory(at: assetRootURL, includingPropertiesForKeys: nil)
for child in existingChildren where child.pathExtension == "dataset" {
    try fileManager.removeItem(at: child)
}

for sample in samples {
    let datasetURL = assetRootURL.appendingPathComponent("\(sample.assetName).dataset", isDirectory: true)
    try fileManager.createDirectory(at: datasetURL, withIntermediateDirectories: true)

    let destination = datasetURL.appendingPathComponent(sample.sourceURL.lastPathComponent)
    if fileManager.fileExists(atPath: destination.path) {
        try fileManager.removeItem(at: destination)
    }
    try fileManager.copyItem(at: sample.sourceURL, to: destination)

    let contents = """
    {
      "data" : [
        {
          "filename" : "\(sample.sourceURL.lastPathComponent)"
        }
      ],
      "info" : {
        "author" : "xcode",
        "version" : 1
      }
    }
    """
    try contents.write(to: datasetURL.appendingPathComponent("Contents.json"), atomically: true, encoding: .utf8)
}

func swiftStringLiteral(_ value: String) -> String {
    "\"" + value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"") + "\""
}

let entries = samples.map {
    "        SampleMIDIFile(title: \(swiftStringLiteral($0.title)), assetName: \(swiftStringLiteral($0.assetName)))"
}.joined(separator: ",\n")

let manifest = """
// Generated by Makefile - do not edit

import Foundation

struct SampleMIDIFile: Sendable, Equatable {
    let title: String
    let assetName: String
}

enum SampleMIDIFiles {
    static let all: [SampleMIDIFile] = [
\(entries)
    ]
}

"""

try fileManager.createDirectory(at: manifestURL.deletingLastPathComponent(), withIntermediateDirectories: true)
try manifest.write(to: manifestURL, atomically: true, encoding: .utf8)

print("Wrote \(samples.count) MIDI sample assets")
