//
//  GeneralMIDI.swift
//  MIDI Scribe
//
//  Created by Codex on 3/21/26.
//

import Foundation

struct GeneralMIDIProgram: Identifiable, Hashable, Sendable {
    let program: Int
    let name: String

    var id: Int { program }
}

enum GeneralMIDI {
    static let programs: [GeneralMIDIProgram] = [
        .init(program: 2, name: "Piano"),
        .init(program: 6, name: "Harpsichord"),
        .init(program: 7, name: "Clavinet"),
        .init(program: 8, name: "Celeste"),
        .init(program: 9, name: "Glockenspiel"),
        .init(program: 10, name: "Music Box"),
        .init(program: 11, name: "Vibraphone"),
        .init(program: 12, name: "Marimba"),
        .init(program: 13, name: "Xylophone"),
        .init(program: 14, name: "Tubular Bells"),
        .init(program: 15, name: "Dulcimer"),
        .init(program: 16, name: "Tonewheel Organ"),
        .init(program: 17, name: "Percussive Organ"),
        .init(program: 18, name: "Rock Organ"),
        .init(program: 19, name: "Pipe Organ"),
        .init(program: 20, name: "Reed Organ"),
        .init(program: 21, name: "Accordion"),
        .init(program: 22, name: "Harmonica"),
        .init(program: 23, name: "Bandoneon"),
        .init(program: 24, name: "Nylon Guitar"),
        .init(program: 25, name: "Steel Guitar"),
        .init(program: 26, name: "Jazz Guitar"),
        .init(program: 27, name: "Clean Guitar"),
        .init(program: 28, name: "Muted Guitar"),
        .init(program: 29, name: "Overdrive Guitar"),
        .init(program: 30, name: "Distortion Guitar"),
        .init(program: 31, name: "Guitar Harmonics"),
        .init(program: 32, name: "Acoustic Bass"),
        .init(program: 33, name: "Finger Bass"),
        .init(program: 34, name: "Pick Bass"),
        .init(program: 35, name: "Fretless Bass"),
        .init(program: 40, name: "Violin"),
        .init(program: 110, name: "Fiddle"),
        .init(program: 41, name: "Viola"),
        .init(program: 42, name: "Cello"),
        .init(program: 43, name: "Double Bass"),
        .init(program: 44, name: "Tremolo Strings"),
        .init(program: 45, name: "Pizzicato Strings"),
        .init(program: 46, name: "Orchestral Harp"),
        .init(program: 48, name: "Fast Strings"),
        .init(program: 49, name: "Slow Strings"),
        .init(program: 50, name: "Synth Strings 1"),
        .init(program: 51, name: "Synth Strings 2"),
        .init(program: 52, name: "Concert Choir"),
        .init(program: 53, name: "Voice Oohs"),
        .init(program: 54, name: "Synth Voice"),
        .init(program: 55, name: "Orchestra Hit"),
        .init(program: 56, name: "Trumpet"),
        .init(program: 57, name: "Trombone"),
        .init(program: 58, name: "Tuba"),
        .init(program: 59, name: "Muted Trumpet"),
        .init(program: 60, name: "French Horns"),
        .init(program: 61, name: "Brass Section"),
        .init(program: 62, name: "Synth Brass 1"),
        .init(program: 63, name: "Synth Brass 2"),
        .init(program: 64, name: "Soprano Sax"),
        .init(program: 65, name: "Alto Sax"),
        .init(program: 66, name: "Tenor Sax"),
        .init(program: 67, name: "Baritone Sax"),
        .init(program: 68, name: "Oboe"),
        .init(program: 69, name: "English Horn"),
        .init(program: 70, name: "Bassoon"),
        .init(program: 71, name: "Clarinet"),
        .init(program: 72, name: "Piccolo"),
        .init(program: 73, name: "Flute"),
        .init(program: 74, name: "Recorder"),
        .init(program: 75, name: "Pan Flute"),
        .init(program: 76, name: "Bottle Blow"),
        .init(program: 77, name: "Shakuhachi"),
        .init(program: 78, name: "Whistle"),
        .init(program: 79, name: "Ocarina"),
        .init(program: 80, name: "Square Lead"),
        .init(program: 81, name: "Saw Lead"),
        .init(program: 82, name: "Synth Calliope"),
        .init(program: 83, name: "Chiffer Lead"),
        .init(program: 84, name: "Charang"),
        .init(program: 85, name: "Solo Vox"),
        .init(program: 86, name: "5th Saw Wave"),
        .init(program: 87, name: "Bass & Lead"),
        .init(program: 88, name: "Fantasia"),
        .init(program: 89, name: "Warm Pad"),
        .init(program: 90, name: "Polysynth"),
        .init(program: 91, name: "Space Voice"),
        .init(program: 92, name: "Bowed Glass"),
        .init(program: 93, name: "Metal Pad"),
        .init(program: 94, name: "Halo Pad"),
        .init(program: 95, name: "Sweep Pad"),
        .init(program: 96, name: "Ice Rain"),
        .init(program: 97, name: "Soundtrack"),
        .init(program: 98, name: "Crystal"),
        .init(program: 99, name: "Atmosphere"),
        .init(program: 100, name: "Brightness"),
        .init(program: 101, name: "Goblin"),
        .init(program: 102, name: "Echo Drops"),
        .init(program: 103, name: "Star Theme"),
        .init(program: 104, name: "Sitar"),
        .init(program: 105, name: "Banjo"),
        .init(program: 106, name: "Shamisen"),
        .init(program: 107, name: "Koto"),
        .init(program: 108, name: "Kalimba"),
        .init(program: 109, name: "Bagpipes"),
        .init(program: 111, name: "Shenai"),
        .init(program: 112, name: "Tinker Bell"),
        .init(program: 113, name: "Agogo"),
        .init(program: 47, name: "Timpani"),
        .init(program: 114, name: "Steel Drums"),
        .init(program: 115, name: "Wood Block"),
        .init(program: 116, name: "Taiko Drum"),
        .init(program: 117, name: "Melodic Tom"),
        .init(program: 118, name: "Synth Drum"),
        .init(program: 119, name: "Reverse Cymbal")
    ]
}
