//
//  GeneralMIDI.swift
//  MIDI Scribe
//
//  Created by Codex on 3/21/26.
//

import Foundation

struct GeneralMIDIProgram: Identifiable, Hashable, Sendable {
    let program: Int
    let name: String

    var id: Int { program }
}

enum GeneralMIDI {
    static let programs: [GeneralMIDIProgram] = [
        .init(program: 0, name: "Acoustic Grand Piano"),
        .init(program: 1, name: "Bright Acoustic Piano"),
        .init(program: 2, name: "Electric Grand Piano"),
        .init(program: 3, name: "Honky-tonk Piano"),
        .init(program: 4, name: "Electric Piano 1"),
        .init(program: 5, name: "Electric Piano 2"),
        .init(program: 6, name: "Harpsichord"),
        .init(program: 7, name: "Clavinet"),
        .init(program: 8, name: "Celesta"),
        .init(program: 9, name: "Glockenspiel"),
        .init(program: 10, name: "Music Box"),
        .init(program: 11, name: "Vibraphone"),
        .init(program: 12, name: "Marimba"),
        .init(program: 13, name: "Xylophone"),
        .init(program: 14, name: "Tubular Bells"),
        .init(program: 15, name: "Dulcimer"),
        .init(program: 16, name: "Drawbar Organ"),
        .init(program: 17, name: "Percussive Organ"),
        .init(program: 18, name: "Rock Organ"),
        .init(program: 19, name: "Church Organ"),
        .init(program: 20, name: "Reed Organ"),
        .init(program: 21, name: "Accordion"),
        .init(program: 22, name: "Harmonica"),
        .init(program: 23, name: "Tango Accordion"),
        .init(program: 24, name: "Acoustic Guitar (nylon)"),
        .init(program: 25, name: "Acoustic Guitar (steel)"),
        .init(program: 26, name: "Electric Guitar (jazz)"),
        .init(program: 27, name: "Electric Guitar (clean)"),
        .init(program: 28, name: "Electric Guitar (muted)"),
        .init(program: 29, name: "Overdriven Guitar"),
        .init(program: 30, name: "Distortion Guitar"),
        .init(program: 31, name: "Guitar Harmonics"),
        .init(program: 32, name: "Acoustic Bass"),
        .init(program: 33, name: "Electric Bass (finger)"),
        .init(program: 34, name: "Electric Bass (pick)"),
        .init(program: 35, name: "Fretless Bass"),
        .init(program: 36, name: "Slap Bass 1"),
        .init(program: 37, name: "Slap Bass 2"),
        .init(program: 38, name: "Synth Bass 1"),
        .init(program: 39, name: "Synth Bass 2"),
        .init(program: 40, name: "Violin"),
        .init(program: 41, name: "Viola"),
        .init(program: 42, name: "Cello"),
        .init(program: 43, name: "Contrabass"),
        .init(program: 44, name: "Tremolo Strings"),
        .init(program: 45, name: "Pizzicato Strings"),
        .init(program: 46, name: "Orchestral Harp"),
        .init(program: 47, name: "Timpani"),
        .init(program: 48, name: "String Ensemble 1"),
        .init(program: 49, name: "String Ensemble 2"),
        .init(program: 50, name: "SynthStrings 1"),
        .init(program: 51, name: "SynthStrings 2"),
        .init(program: 52, name: "Choir Aahs"),
        .init(program: 53, name: "Voice Oohs"),
        .init(program: 54, name: "Synth Voice"),
        .init(program: 55, name: "Orchestra Hit"),
        .init(program: 56, name: "Trumpet"),
        .init(program: 57, name: "Trombone"),
        .init(program: 58, name: "Tuba"),
        .init(program: 59, name: "Muted Trumpet"),
        .init(program: 60, name: "French Horn"),
        .init(program: 61, name: "Brass Section"),
        .init(program: 62, name: "SynthBrass 1"),
        .init(program: 63, name: "SynthBrass 2"),
        .init(program: 64, name: "Soprano Sax"),
        .init(program: 65, name: "Alto Sax"),
        .init(program: 66, name: "Tenor Sax"),
        .init(program: 67, name: "Baritone Sax"),
        .init(program: 68, name: "Oboe"),
        .init(program: 69, name: "English Horn"),
        .init(program: 70, name: "Bassoon"),
        .init(program: 71, name: "Clarinet"),
        .init(program: 72, name: "Piccolo"),
        .init(program: 73, name: "Flute"),
        .init(program: 74, name: "Recorder"),
        .init(program: 75, name: "Pan Flute"),
        .init(program: 76, name: "Blown Bottle"),
        .init(program: 77, name: "Shakuhachi"),
        .init(program: 78, name: "Whistle"),
        .init(program: 79, name: "Ocarina"),
        .init(program: 80, name: "Lead 1 (square)"),
        .init(program: 81, name: "Lead 2 (sawtooth)"),
        .init(program: 82, name: "Lead 3 (calliope)"),
        .init(program: 83, name: "Lead 4 (chiff)"),
        .init(program: 84, name: "Lead 5 (charang)"),
        .init(program: 85, name: "Lead 6 (voice)"),
        .init(program: 86, name: "Lead 7 (fifths)"),
        .init(program: 87, name: "Lead 8 (bass + lead)"),
        .init(program: 88, name: "Pad 1 (new age)"),
        .init(program: 89, name: "Pad 2 (warm)"),
        .init(program: 90, name: "Pad 3 (polysynth)"),
        .init(program: 91, name: "Pad 4 (choir)"),
        .init(program: 92, name: "Pad 5 (bowed)"),
        .init(program: 93, name: "Pad 6 (metallic)"),
        .init(program: 94, name: "Pad 7 (halo)"),
        .init(program: 95, name: "Pad 8 (sweep)"),
        .init(program: 96, name: "FX 1 (rain)"),
        .init(program: 97, name: "FX 2 (soundtrack)"),
        .init(program: 98, name: "FX 3 (crystal)"),
        .init(program: 99, name: "FX 4 (atmosphere)"),
        .init(program: 100, name: "FX 5 (brightness)"),
        .init(program: 101, name: "FX 6 (goblins)"),
        .init(program: 102, name: "FX 7 (echoes)"),
        .init(program: 103, name: "FX 8 (sci-fi)"),
        .init(program: 104, name: "Sitar"),
        .init(program: 105, name: "Banjo"),
        .init(program: 106, name: "Shamisen"),
        .init(program: 107, name: "Koto"),
        .init(program: 108, name: "Kalimba"),
        .init(program: 109, name: "Bag pipe"),
        .init(program: 110, name: "Fiddle"),
        .init(program: 111, name: "Shanai"),
        .init(program: 112, name: "Tinkle Bell"),
        .init(program: 113, name: "Agogo"),
        .init(program: 114, name: "Steel Drums"),
        .init(program: 115, name: "Woodblock"),
        .init(program: 116, name: "Taiko Drum"),
        .init(program: 117, name: "Melodic Tom"),
        .init(program: 118, name: "Synth Drum"),
        .init(program: 119, name: "Reverse Cymbal"),
        .init(program: 120, name: "Guitar Fret Noise"),
        .init(program: 121, name: "Breath Noise"),
        .init(program: 122, name: "Seashore"),
        .init(program: 123, name: "Bird Tweet"),
        .init(program: 124, name: "Telephone Ring"),
        .init(program: 125, name: "Helicopter"),
        .init(program: 126, name: "Applause"),
        .init(program: 127, name: "Gunshot")
    ]
}
